# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.2
language: objective-c
cache: cocoapods
podfile: Podfile
before_install:
- gem install cocoapods 
- pod repo add BMPodSpecs https://github.com/werner77/BMPodSpecs.git
- pod install
script:
- set -o pipefail && xcodebuild clean build -workspace MappableObjectGenerator.xcworkspace -scheme MappableObjectGenerator ONLY_ACTIVE_ARCH=NO | xcpretty

